Added stats submodule check in make-doodle. Updated build instructions in readme.

diff --git a/build/make-doodle b/build/make-doodle
--- a/build/make-doodle
+++ b/build/make-doodle
@@ -24,6 +24,8 @@ PROJECT_HOME="$PWD"
 DEBUG_OUT_FILE="$PROJECT_HOME/build/doodle-debug.js"
 MIN_OUT_FILE="$PROJECT_HOME/build/doodle.js"
 CLOSURE_COMPILER="$PROJECT_HOME/build/compiler.jar"
+#submodules
+STATS_FILE="$PROJECT_HOME/lib/stats/src/Stats.js"
 #compiler options
 COMPILATION_LEVEL=1 #whitespace, [simple], advanced
 WARNING_LEVEL=1 #quiet, [default], verbose
@@ -35,7 +37,7 @@ function build_full {
     cat ./src/utils.js >> "$DEBUG_OUT_FILE"
     
     echo "/*DEBUG_STATS*/" >> "$DEBUG_OUT_FILE"
-    cat ./lib/stats/src/Stats.js >> "$DEBUG_OUT_FILE"
+    cat "$STATS_FILE" >> "$DEBUG_OUT_FILE"
     echo "/*END_DEBUG_STATS*/" >> "$DEBUG_OUT_FILE"
 
     #constants
@@ -170,6 +172,14 @@ while getopts "hcJ:dDPSW:C:" option; do
         \?) print_help_and_exit;;
     esac
 done
+
+#check for submodules
+if [ ! -f "$STATS_FILE" ]; then
+    echo "Please update the required submodule(s)."
+    echo "  > git submodule init"
+    echo "  > git submodule update"
+    exit 1;
+fi
 
 parse_compiler_options
 
